[package]
name = "duct_reader_check"
version = "0.1.0"
edition = "2021"

[dependencies]
duct = "0.13.7"
env_logger = "0.11.6"
filedescriptor = "0.8.3"
log = "0.4.25"
os_pipe = "1.2.1"
pyo3 = "0.23.4"
